using System.Collections.Generic;

namespace DotnetGraph.Extension.Services;

internal static class GraphLocalizer
{
    public static string T(string key) =>
        UserGraphSettings.UiLanguage switch
        {
            GraphUiLanguage.English => En(key),
            GraphUiLanguage.Spanish => Es(key),
            _ => Pt(key)
        };

    private static string Pt(string key) => key switch
    {
        "Title" => "Dotnet Graph",
        "Theme" => "Tema",
        "ThemeSystem" => "Sistema",
        "ThemeLight" => "Claro",
        "ThemeDark" => "Escuro",
        "Refresh" => "Atualizar",
        "Architecture" => "Arquitetura",
        "CallGraph" => "Call Graph",
        "Namespaces" => "Namespaces",
        "SectionProjectRefs" => "REFERÊNCIAS DE PROJETO",
        "SectionPackages" => "PACOTES NUGET",
        "SectionTypes" => "TIPOS / MÓDULOS",
        "SectionSourceFiles" => "ARQUIVOS DO CLUSTER",
        "SectionCallMethods" => "MÉTODOS (CALL GRAPH)",
        "CopyRefs" => "Copiar referências de projeto",
        "ExportRefs" => "Exportar referências de projeto (.txt)",
        "ClosePanel" => "Fechar painel",
        "LoadingDetails" => "Carregando detalhes...",
        "CircularDetected" => "Dependência circular detectada",
        "Path" => "Caminho:",
        "HighlightCycle" => "Destacar no grafo",
        "Language" => "Idioma",
        "LangBr" => "BR",
        "LangEn" => "EN",
        "LangEs" => "ES",
        "TooltipArchitecture" => "Grafo de projetos da solução",
        "TooltipCallGraph" => "Call graph do projeto selecionado (C#)",
        "TooltipNamespaces" => "Mapa de clusters por namespace (C#)",
        "LoadingInit" => "Inicializando visualização...",
        "LoadingAnalyze" => "Analisando projetos da solução...",
        "LoadingNamespace" => "Montando mapa de namespaces...",
        "LoadingCallGraph" => "Montando call graph...",
        "ViewArchitecture" => "Visão: arquitetura (projetos)",
        "ViewArchitectureCycles" => "Visão: arquitetura · ⚠ {0} dependência(s) circular(es)",
        "ViewNamespaces" => "Visão: namespaces · {0}",
        "ViewCallGraph" => "Visão: call graph · {0}",
        "WebEmptyGraph" => "Nenhum projeto no grafo — use Atualizar na barra superior",
        "WebEmptyGraphHint" => "O grafo ocupa toda a área até você selecionar um projeto.",
        "WebMethods" => "método(s)",
        "WebCalls" => "chamada(s)",
        "WebClusters" => "cluster(s)",
        "WebLinks" => "ligação(ões)",
        "WebProjects" => "projeto(s)",
        "WebReferences" => "referência(s)",
        "WebCycles" => "ciclo(s)",
        "WebFocus" => "Foco",
        "WebNamespaceMap" => "Namespace map",
        "WebTypesCount" => "tipos",
        _ => key
    };

    private static string En(string key) => key switch
    {
        "Title" => "Dotnet Graph",
        "Theme" => "Theme",
        "ThemeSystem" => "System",
        "ThemeLight" => "Light",
        "ThemeDark" => "Dark",
        "Refresh" => "Refresh",
        "Architecture" => "Architecture",
        "CallGraph" => "Call Graph",
        "Namespaces" => "Namespaces",
        "SectionProjectRefs" => "PROJECT REFERENCES",
        "SectionPackages" => "NUGET PACKAGES",
        "SectionTypes" => "TYPES / MODULES",
        "SectionSourceFiles" => "CLUSTER FILES",
        "SectionCallMethods" => "METHODS (CALL GRAPH)",
        "CopyRefs" => "Copy project references",
        "ExportRefs" => "Export project references (.txt)",
        "ClosePanel" => "Close panel",
        "LoadingDetails" => "Loading details...",
        "CircularDetected" => "Circular dependency detected",
        "Path" => "Path:",
        "HighlightCycle" => "Highlight on graph",
        "Language" => "Language",
        "LangBr" => "BR",
        "LangEn" => "EN",
        "LangEs" => "ES",
        "TooltipArchitecture" => "Solution project graph",
        "TooltipCallGraph" => "Call graph for selected C# project",
        "TooltipNamespaces" => "Namespace cluster map (C#)",
        "LoadingInit" => "Initializing view...",
        "LoadingAnalyze" => "Analyzing solution projects...",
        "LoadingNamespace" => "Building namespace map...",
        "LoadingCallGraph" => "Building call graph...",
        "ViewArchitecture" => "View: architecture (projects)",
        "ViewArchitectureCycles" => "View: architecture · ⚠ {0} circular dependency(ies)",
        "ViewNamespaces" => "View: namespaces · {0}",
        "ViewCallGraph" => "View: call graph · {0}",
        "WebEmptyGraph" => "No projects in graph — use Refresh in the toolbar",
        "WebEmptyGraphHint" => "The graph fills the area until you select a project.",
        "WebMethods" => "method(s)",
        "WebCalls" => "call(s)",
        "WebClusters" => "cluster(s)",
        "WebLinks" => "link(s)",
        "WebProjects" => "project(s)",
        "WebReferences" => "reference(s)",
        "WebCycles" => "cycle(s)",
        "WebFocus" => "Focus",
        "WebNamespaceMap" => "Namespace map",
        "WebTypesCount" => "types",
        _ => key
    };

    private static string Es(string key) => key switch
    {
        "Title" => "Dotnet Graph",
        "Theme" => "Tema",
        "ThemeSystem" => "Sistema",
        "ThemeLight" => "Claro",
        "ThemeDark" => "Oscuro",
        "Refresh" => "Actualizar",
        "Architecture" => "Arquitectura",
        "CallGraph" => "Call Graph",
        "Namespaces" => "Namespaces",
        "SectionProjectRefs" => "REFERENCIAS DE PROYECTO",
        "SectionPackages" => "PAQUETES NUGET",
        "SectionTypes" => "TIPOS / MÓDULOS",
        "SectionSourceFiles" => "ARCHIVOS DEL CLUSTER",
        "SectionCallMethods" => "MÉTODOS (CALL GRAPH)",
        "CopyRefs" => "Copiar referencias de proyecto",
        "ExportRefs" => "Exportar referencias de proyecto (.txt)",
        "ClosePanel" => "Cerrar panel",
        "LoadingDetails" => "Cargando detalles...",
        "CircularDetected" => "Dependencia circular detectada",
        "Path" => "Ruta:",
        "HighlightCycle" => "Resaltar en el grafo",
        "Language" => "Idioma",
        "LangBr" => "BR",
        "LangEn" => "EN",
        "LangEs" => "ES",
        "TooltipArchitecture" => "Grafo de proyectos de la solución",
        "TooltipCallGraph" => "Call graph del proyecto C# seleccionado",
        "TooltipNamespaces" => "Mapa de clusters por namespace (C#)",
        "LoadingInit" => "Inicializando vista...",
        "LoadingAnalyze" => "Analizando proyectos de la solución...",
        "LoadingNamespace" => "Generando mapa de namespaces...",
        "LoadingCallGraph" => "Generando call graph...",
        "ViewArchitecture" => "Vista: arquitectura (proyectos)",
        "ViewArchitectureCycles" => "Vista: arquitectura · ⚠ {0} dependencia(s) circular(es)",
        "ViewNamespaces" => "Vista: namespaces · {0}",
        "ViewCallGraph" => "Vista: call graph · {0}",
        "WebEmptyGraph" => "Sin proyectos en el grafo — use Actualizar en la barra",
        "WebEmptyGraphHint" => "El grafo ocupa el área hasta que seleccione un proyecto.",
        "WebMethods" => "método(s)",
        "WebCalls" => "llamada(s)",
        "WebClusters" => "cluster(s)",
        "WebLinks" => "enlace(s)",
        "WebProjects" => "proyecto(s)",
        "WebReferences" => "referencia(s)",
        "WebCycles" => "ciclo(s)",
        "WebFocus" => "Foco",
        "WebNamespaceMap" => "Mapa de namespaces",
        "WebTypesCount" => "tipos",
        _ => key
    };

    public static IReadOnlyDictionary<string, string> WebStrings() => new Dictionary<string, string>
    {
        ["emptyGraph"] = T("WebEmptyGraph"),
        ["emptyGraphHint"] = T("WebEmptyGraphHint"),
        ["methods"] = T("WebMethods"),
        ["calls"] = T("WebCalls"),
        ["clusters"] = T("WebClusters"),
        ["links"] = T("WebLinks"),
        ["projects"] = T("WebProjects"),
        ["references"] = T("WebReferences"),
        ["cycles"] = T("WebCycles"),
        ["focus"] = T("WebFocus"),
        ["callGraph"] = T("CallGraph"),
        ["namespaceMap"] = T("WebNamespaceMap"),
        ["typesCount"] = T("WebTypesCount")
    };
}
